name: Run SQL Migrations

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  migrate:
    name: Run migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          chmod +x ./scripts/run_migrations.sh
          ./scripts/run_migrations.sh
